services:
  wp-db:
    image: mariadb
    volumes:
      - wp-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress

  wp:
    image: wordpress:6.5
    ports:
      - "3080:80"
    volumes:
      - wp-wordpress:/var/www/html
      - ./UnivaPay-for-WooCommerce:/var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce
      - ./custom-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
    depends_on:
      - wp-db
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    entrypoint: ["sh", "/usr/local/bin/custom-entrypoint.sh"]

  # WP-CLI service for wordpress cli, composer, and testing tools
  wp-cli:
    build:
      context: .
      dockerfile: Dockerfile.wp-cli
    volumes_from:
      - wp
    volumes:
      - wp-cli-tmp:/tmp # Temporary volume for WordPress test library
    depends_on:
      - wp-db
      - wp
    working_dir: /var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_CLI_CACHE_DIR: /tmp/.wp-cli/cache  # cache directory to a writable location
      COMPOSER_CACHE_DIR: /tmp/.composer/cache  # cache directory to a writable location
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
      WP_TESTS_PHPUNIT_POLYFILLS_PATH: /var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce/vendor/yoast/phpunit-polyfills
    user: "33:33"
    command: "--info"

volumes:
  wp-mariadb:
  wp-wordpress:
  wp-cli-tmp:
  