services:
  wp-db:
    container_name: wp-db
    image: mariadb
    volumes:
      - wp-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 3s 
      interval: 10s
      timeout: 5s
      retries: 3

  wp:
    container_name: wp
    build: .
    ports:
      - "${WP_PORT:-80}:80"
    volumes:
      - wp-wordpress:/var/www/html
      - ./UnivaPay-for-WooCommerce:/var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce
    depends_on:
      wp-db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WP_PORT: ${WP_PORT:-80}
      E2E_TOKEN: ${E2E_TOKEN}
      E2E_SECRET: ${E2E_SECRET}
      E2E_API_URL: ${E2E_API_URL}
      E2E_WIDGET_URL: ${E2E_WIDGET_URL}
      E2E_FORMURL: ${E2E_FORMURL}
      E2E_CAPTURE: yes
      E2E_UNIVAPAY_ADMIN_CONSOLE_URL: ${E2E_UNIVAPAY_ADMIN_CONSOLE_URL}
      E2E_UNIVAPAY_ADMIN_EMAIL: ${E2E_UNIVAPAY_ADMIN_EMAIL}
      E2E_UNIVAPAY_ADMIN_PASSWORD: ${E2E_UNIVAPAY_ADMIN_PASSWORD}
  
volumes:
  wp-mariadb:
  wp-wordpress:
