services:
  wp-db:
    container_name: wp-db
    image: mariadb
    volumes:
      - wp-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress

  wp:
    container_name: wp
    build: .
    ports:
      - "${WP_PORT:-3080}:80"
    volumes:
      - wp-wordpress:/var/www/html
      - ./UnivaPay-for-WooCommerce:/var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce
    depends_on:
      - wp-db
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WP_PORT: ${WP_PORT:-3080}
  
volumes:
  wp-mariadb:
  wp-wordpress:
