name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "latest"
    - uses: "ramsey/composer-install@v3"
      with:
        args: "--no-dev"
        working-directory: "UnivaPay-for-WooCommerce"
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install npm dependencies
      run: npm ci
      working-directory: "UnivaPay-for-WooCommerce"
    - name: Run npm build
      run: npm run build
      working-directory: "UnivaPay-for-WooCommerce"
    - name: Create artifact directory
      run: mkdir -p ./artifact
      working-directory: "UnivaPay-for-WooCommerce"
    - name: Create tarball excluding .distignore files
      run: tar --exclude-vcs --exclude-from=".distignore" --exclude="./artifact" -czf ./artifact/build-artifacts.tar.gz .
      working-directory: "UnivaPay-for-WooCommerce"
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./UnivaPay-for-WooCommerce/artifact/build-artifacts.tar.gz
        retention-days: 7
