name: Wordpress & Plugins Setup

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      wordpress-version:
        required: true
        type: string
      woocommerce-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: UnivaPay-for-WooCommerce
    services:
      wp-db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress_test
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4

    - name: Install SVN
      run: sudo apt-get update && sudo apt-get install -y subversion

    - name: Cache Composer Dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}

    - name: Install Composer Dependencies
      run: composer install

    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp

    - uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install NPM Dependencies
      run: npm ci

    - name: Run NPM Build
      run: npm run build
