name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: UnivaPay-for-WooCommerce
    steps:
    - name: Call Common Steps
      uses: ./.github/workflows/common-steps.yml
      with:
        php-version: '8.2'
        wordpress-version: 'latest'
        woocommerce-version: '9.3.3'

    - name: Run Docker Compose
      run: docker compose up -d

    - name: Run E2E Tests Block Checkout
      run: |
        docker compose exec wp /bin/bash -c "cd /var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce && composer init:e2e && npm run test:e2e:block"

    - name: Run E2E Tests Classic Checkout
      run: |
        docker compose exec wp /bin/bash -c "cd /var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce && composer init:e2e && ./bin/wc-checkout-change-layout.sh && npm run test:e2e:classic"

