name: E2E Test

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/workflows/common
      with:
        php-version: '8.2'

    - name: Run Docker Compose
      run: docker compose up -d

    - name: Run E2E Tests Block Checkout
      run: |
        docker compose exec wp /bin/bash -c "cd /var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce && composer init:e2e && npm run test:e2e:block"

    - name: Run E2E Tests Classic Checkout
      run: |
        docker compose exec wp /bin/bash -c "cd /var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce && composer init:e2e && ./bin/wc-checkout-change-layout.sh && npm run test:e2e:classic"
