name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "latest"
    - uses: "ramsey/composer-install@v2"
      with:
        working-directory: "UnivaPay-for-WooCommerce"
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: univapay-for-wc
        BUILD_DIR: UnivaPay-for-WooCommerce
