name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        php-version: ['7.4', '8.2']
        wordpress-version: ['6.2.2', 'latest']
        woocommerce-version: ['8.2.0', 'latest']
        exclude:
          - wordpress-version: '6.2.2'
            woocommerce-version: 'latest'
      max-parallel: 2
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: UnivaPay-for-WooCommerce
    services:
      wp-db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress_test
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Install Composer dependencies
      run: composer install
    - name: WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install npm dependencies
      run: npm ci
    - name: Run npm build
      run: npm run build
    - name: Prep WordPress & plugins environment
      run: |
        bin/install-wp-tests.sh wordpress_test root wordpress 127.0.0.1 ${{ matrix.wordpress-version }}
        cp wp-tests-config.php /tmp/wordpress-tests-lib/wp-tests-config.php
        wp config create --dbname=wordpress_test --dbuser=root --dbpass=wordpress --dbhost=127.0.0.1 --path=/tmp/wordpress
        wp core install --url=http://localhost --title=TestWP --admin_user=admin --admin_password=admin --admin_email=test@example.com --path=/tmp/wordpress
        wp plugin install woocommerce --version=${{ matrix.woocommerce-version }} --activate --path=/tmp/wordpress
        cp -r . /tmp/wordpress/wp-content/plugins/UnivaPay-for-WooCommerce
        rm -rf /tmp/wordpress/wp-content/plugins/UnivaPay-for-WooCommerce/vendor
    - name: Update wp-tests-config.php
      run: sed -i "s/define('DB_HOST', .*/define('DB_HOST', '127.0.0.1:3306');/" /tmp/wordpress-tests-lib/wp-tests-config.php
    - name: Run test
      run: ./vendor/bin/phpunit --configuration phpunit.xml
    - name: Prep E2E environment
      run: composer init:e2e
    - name: Run e2e test for block checkout
      run: npm run test:e2e:block
    - name: Run e2e test for classic checkout
      run: npm run test:e2e:classic

